SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)

# specify the cross compiler
SET(CMAKE_C_COMPILER
$ENV{XTOOLS_PATH}/$ENV{XTOOLS}/bin/$ENV{XTOOLS}-gcc)

SET(CMAKE_CXX_COMPILER
$ENV{XTOOLS_PATH}/$ENV{XTOOLS}/bin/$ENV{XTOOLS}-g++)

# where is the target environment
SET(CMAKE_FIND_ROOT_PATH
$ENV{XTOOLS_PATH}/$ENV{XTOOLS})

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)